services:
    app:
        build:
            context: ./app/docker
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.3/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        env_file:
            - .env
        volumes:
            - './app:/var/www/html'
        networks:
            - sail
        depends_on:
            - pgsql
    frontend:
        build:
            context: ./frontend/docker
            dockerfile: Dockerfile
        tty: true
        volumes:
            - './frontend:/var/www/html'
        networks:
            - sail
    pgsql:
        image: postgres:15
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        environment:
            PGPASSWORD: '${DB_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'vol_database:/var/lib/postgresql/data'
        networks:
            - sail
volumes:
    vol_database:
        driver: local

networks:
    sail:
        driver: bridge
